name: Tamimystic OS ESP32 Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-esp32:
    name: Build ESP32-S3 Firmware
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.2
          target: esp32s3
          

      - name: Archive Firmware (BIN Files)
        uses: actions/upload-artifact@v4
        with:
          name: tamimystic_os_firmware
          path: |
            build/tamimystic_os.bin
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
            build/tamimystic_os.elf
